### ISSUE TITLE
设置工作模式

### ISSUE THREAD

**Issue by redstonee** [tuya/tuya-wifi-mcu-sdk-arduino-library#4]
《串口协议》中提到模组的工作模式有• MCU 与模组配合处理模式和• 模组自处理模式，请问使用该Arduino库如何实现模组自处理模式？

**Comment by shiliu-yang** [comment]
该功能将会在下个版本进行添加。你也可以参考涂鸦的WiFi mcu sdk在config.h中加入下列代码:
```c
#define         WIFI_CONTROL_SELF_MODE                       //Wi-Fi 自处理按键及LED指示灯，如为MCU外接按键/LED指示灯请关闭该宏

#ifdef          WIFI_CONTROL_SELF_MODE                        //模块自处理
	#define     WF_STATE_KEY            14                    //Wi-Fi 模块状态指示按键，请根据实际 GPIO 管脚设置
	#define     WF_RESERT_KEY           0                     //Wi-Fi 模块重置按键，请根据实际 GPIO 管脚设置
#endif
```

**Comment by redstonee** [comment]
謝謝！


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月12日 10:03:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tuya/tuya-wifi-mcu-sdk-arduino-library] 设置工作模式 (#4)




 
该功能将会在下个版本进行添加。你也可以参考涂鸦的WiFi mcu sdk在config.h中加入下列代码:
 #define         WIFI_CONTROL_SELF_MODE                       //Wi-Fi 自处理按键及LED指示灯，如为MCU外接按键/LED指示灯请关闭该宏 #ifdef          WIFI_CONTROL_SELF_MODE                        //模块自处理 #define     WF_STATE_KEY            14                    //Wi-Fi 模块状态指示按键，请根据实际 GPIO 管脚设置 #define     WF_RESERT_KEY           0                     //Wi-Fi 模块重置按键，请根据实际 GPIO 管脚设置 #endif

**Comment by redstonee** [comment]
加入上述代码后编译报错：
```
C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp: In member function 'void TuyaWifi::mcu_set_wifi_mode(unsigned char)':

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp:964:5: error: 'set_wifimode_flag' was not declared in this scope

     set_wifimode_flag = SET_WIFICONFIG_ERROR;

     ^~~~~~~~~~~~~~~~~

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp: In member function 'unsigned char TuyaWifi::mcu_get_wifi_work_state()':

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp:986:12: error: 'wifi_work_state' was not declared in this scope

     return wifi_work_state;

            ^~~~~~~~~~~~~~~

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp:986:12: note: suggested alternative: 'mcu_get_wifi_work_state'

     return wifi_work_state;

            ^~~~~~~~~~~~~~~

            mcu_get_wifi_work_state

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp: In member function 'void TuyaWifi::mcu_reset_wifi()':

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp:999:5: error: 'reset_wifi_flag' was not declared in this scope

     reset_wifi_flag = RESET_WIFI_ERROR;

     ^~~~~~~~~~~~~~~

C:\Users\RedStone\Documents\Arduino\libraries\Tuya_WiFi_MCU_SDK\src\TuyaWifi.cpp:999:5: note: suggested alternative: 'mcu_set_wifi_mode'

     reset_wifi_flag = RESET_WIFI_ERROR;

     ^~~~~~~~~~~~~~~

     mcu_set_wifi_mode

exit status 1

```

**Comment by shiliu-yang** [comment]
你还需要在TuyaWiFi.h 中(第34-38行)把下面功能打开。
```c
// #ifndef WIFI_CONTROL_SELF_MODE
TUYA_GLOBAL_EXTERN volatile unsigned char reset_wifi_flag;   //Reset wifi flag (TRUE: successful / FALSE: failed)
TUYA_GLOBAL_EXTERN volatile unsigned char set_wifimode_flag; //Set the WIFI working mode flag (TRUE: Success / FALSE: Failed)
TUYA_GLOBAL_EXTERN volatile unsigned char wifi_work_state;   //Wifi module current working status
// #endif
```

该功能打开后编译可以过，但是整体功能没有经过测试。建议你获取到MCU SDK后参考涂鸦文档中心中的[MCU SDK 移植](https://developer.tuya.com/cn/docs/iot/overview-of-migrating-tuyas-mcu-sdk?id=K9hhi0xr5vll9)对arduino库进行修改。

**Comment by redstonee** [comment]
果然是Gayhub上的開發者靠譜！


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月13日 16:14:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tuya/tuya-wifi-mcu-sdk-arduino-library] 设置工作模式 (#4)




 
你还需要在TuyaWiFi.h 中(第34-38行)把下面功能打开。
 // #ifndef WIFI_CONTROL_SELF_MODE TUYA_GLOBAL_EXTERN volatile unsigned char reset_wifi_flag;   //Reset wifi flag (TRUE: successful / FALSE: failed) TUYA_GLOBAL_EXTERN volatile unsigned char set_wifimode_flag; //Set the WIFI working mode flag (TRUE: Success / FALSE: Failed) TUYA_GLOBAL_EXTERN volatile unsigned char wifi_work_state;   //Wifi module current working status // #endif
 
该功能打开后编译可以过，但是整体功能没有经过测试。建议你获取到MCU SDK后参考涂鸦文档中心中的MCU SDK 移植对arduino库进行修改。
