### ISSUE TITLE
dp_process callback stops after receiveing some Dreamlight scene mode raw data.

### ISSUE THREAD

**Issue by REDHUN** [tuya/tuya-wifi-mcu-sdk-arduino-library#5]
I am trying to build a Tuya based individual addressable led strip.
the data from the module is in raw format and it looks like this.
```
Receiving module DP sends information           [2021/08/31 13:36:27.60]
dpid: 51
name: Dreamlight scene mode
type: raw
value: 01 03 00 00 00 80 00 00 64 00 F0 64 00 3D 64 00 00 64 00 AE 64 01 13 64 00 78 64 
55 AA 00 06 00 1F 33 00 00 1B 01 03 00 00 00 80 00 00 64 00 F0 64 00 3D 64 00 00 64 00 AE 64 01 13 64 00 78 64 19

```
After selecting some options like "Christmas eve" the dp_process callback stops working need to restart the mcu.
But everything works on the Tuya debug assistant. the mcu not crashed all the processes only not receive any updates on dp_process.
Not all of the Dreamlight scene causes this issue only few do.
Please fix this bug as soon as possible.
Thanks in advance.

**Comment by REDHUN** [comment]
Here my code.
unsigned char dp_process(unsigned char dpid, const unsigned char value[], unsigned short length)
{
  state = my_device.mcu_get_dp_download_data(dpid, value, length);
  for (int i = 0; i < length; i++)
  {
    Serial.print(value[i], HEX);
  }
  if (length>7 && length <=14)
  {
      uint8_t version_number  = (uint8_t) value[0];
      uint8_t scene_mode_number = (uint8_t) value[1];
      uint8_t change_mode  = (uint8_t) value[2];
      uint8_t switching_interval  = (uint8_t) value[3];
      uint8_t change_time  = (uint8_t) value[4];
      // fgh setting item
      uint8_t brightness  = (uint8_t) value[8];
      uint16_t colour1 = ((uint16_t)value[9] << 8) | value[10];
      uint8_t saturation1  = (uint8_t) value[11];
      uint16_t colour2 = ((uint16_t)value[11] << 8) | value[12];
      uint8_t saturation2  = (uint8_t) value[13];

      Serial.print("version \t");
      Serial.println(version_number, HEX);

      Serial.print("mode \t");
      Serial.println(scene_mode_number, HEX);

      Serial.print("change mode \t");
      Serial.println(change_mode, HEX);

      Serial.print("switching interval \t");
      Serial.println(switching_interval, HEX);

      Serial.print("change time \t");
      Serial.println(change_time, HEX);

      Serial.print("brightness \t");
      Serial.println(brightness, HEX);

      Serial.print("colour1 \t");
      Serial.println(colour1, HEX);

      Serial.print("saturation1 \t");
      Serial.println(saturation2, HEX);

      Serial.print("colour2 \t");
      Serial.println(colour1, HEX);

      Serial.print("saturation2 \t");
      Serial.println(saturation2, HEX);
  }
  
  switch (dpid){
    case DPID_SWITCH_LED: {
      break;
    }
    case DPID_WORK_MODE: {
      break;
    }
    case DPID_BRIGHT_VALUE: {
      break;
    }
    case DPID_TEMP_VALUE: {
      break;
    }
    case DPID_COLOUR_DATA: {
      break;
    }
    case DPID_SCENE_DATA: {

      break;
    }
    case DPID_COUNTDOWN: {
      break;
    }
    case DPID_MUSIC_DATA: {
      break;
    }
    case DPID_CONTROL_DATA: {
      break;
    }
    case DPID_POWER_MEMORY: {
      break;
    }
    case DPID_DREAMLIGHT_SCENE_MODE: {
      break;
    }
    case DPID_DREAMLIGHTMIC_MUSIC_DATA: {
      break;
    }
    case DPID_LIGHTPIXEL_NUMBER_SET: {
      break;
    }
    default:
      break;
  }
  my_device.mcu_dp_update(dpid, value, length);
}

**Comment by shiliu-yang** [comment]
The possible cause of this problem is caused by the MCU serial port's receive cache being too small.

Expand the receive cache in the `config.h` file of the "Tuya_WiFi_MCU_SDK" library.

You may need to expand these three macros "WIFI_UART_RECV_BUF_LMT", "WIFI_DATA_PROCESS_LMT" and "WIFIR_UART_SEND_BUF_LMT".

Example：
```
#ifndef SUPPORT_MCU_FIRM_UPDATE
#define WIFI_UART_RECV_BUF_LMT 255 //UART data receiving buffer size, can be reduced if the MCU has insufficient RAM
#define WIFI_DATA_PROCESS_LMT 255  //UART data processing buffer size, according to the user DP data size, must be greater than 24
#else
#define WIFI_UART_RECV_BUF_LMT 128 //UART data receiving buffer size, can be reduced if the MCU has insufficient RAM

/*  Select the appropriate UART data processing buffer size here 
    (select the buffer size based on the size selected by the above MCU firmware upgrade package and whether to turn on the weather service)  */
#define WIFI_DATA_PROCESS_LMT 1000 //UART data processing buffer size. If the MCU firmware upgrade is required, the single-packet size is 256, the buffer must be greater than 260, or larger if the weather service is enabled
//#define WIFI_DATA_PROCESS_LMT           600             //UART data processing buffer size. If the MCU firmware upgrade is required, the single-packet size is 512, the buffer must be greater than 520, or larger if the weather service is enabled
//#define WIFI_DATA_PROCESS_LMT           1200            //UART data processing buffer size. If the MCU firmware upgrade is required, the single-packet size is 1024, the buffer must be greater than 1030, or larger if the weather service is enabled

#endif

#define WIFIR_UART_SEND_BUF_LMT 255 //According to the user's DP data size, it must be greater than 48
```

**Comment by REDHUN** [comment]
I am tried this configuration and still have the issue.
changes that i made.
#define WIFI_UART_RECV_BUF_LMT 255
#define WIFI_DATA_PROCESS_LMT 255
#define WIFIR_UART_SEND_BUF_LMT 255

**Comment by REDHUN** [comment]
after some debugging i have found that it get stuck on 
the while loop inside TuyaWifi.cpp not calling data_handle method

```
 while ((rx_in - offset) >= PROTOCOL_HEAD)
    {
        if (tuya_uart.wifi_data_process_buf[offset + HEAD_FIRST] != FRAME_FIRST)
        {
            offset++;
            continue;
        }

        if (tuya_uart.wifi_data_process_buf[offset + HEAD_SECOND] != FRAME_SECOND)
        {
            offset++;
            continue;
        }

        if (tuya_uart.wifi_data_process_buf[offset + PROTOCOL_VERSION] != MCU_RX_VER)
        {
            offset += 2;
            continue;
        }

        rx_value_len = tuya_uart.wifi_data_process_buf[offset + LENGTH_HIGH] * 0x100;
        rx_value_len += (tuya_uart.wifi_data_process_buf[offset + LENGTH_LOW] + PROTOCOL_HEAD);
        if (rx_value_len > sizeof(tuya_uart.wifi_data_process_buf) + PROTOCOL_HEAD)
        {
            offset += 3;
            continue;
        }

        if ((rx_in - offset) < rx_value_len)
        {
            break;
        }

        //数据接收完成
        if (tuya_tools.get_check_sum((unsigned char *)tuya_uart.wifi_data_process_buf + offset, rx_value_len - 1) != tuya_uart.wifi_data_process_buf[offset + rx_value_len - 1])
        {
            //校验出错
            //printf("crc error (crc:0x%X  but data:0x%X)\r\n",get_check_sum((unsigned char *)wifi_data_process_buf + offset,rx_value_len - 1),wifi_data_process_buf[offset + rx_value_len - 1]);
            offset += 3;
            continue;
        }

        data_handle(offset);
        offset += rx_value_len;
    } //end while
```

**Comment by REDHUN** [comment]
if ((rx_in - offset) < rx_value_len)
        {
            break;
        }
This is the cause of the problem

**Comment by shiliu-yang** [comment]
The program break here means that the DP data received by MCU is not complete.

**Comment by REDHUN** [comment]
Thank you @shiliu-yang it worked
#define WIFI_UART_RECV_BUF_LMT 32
#define WIFI_DATA_PROCESS_LMT 64
#define WIFIR_UART_SEND_BUF_LMT 64
